// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Quit():void;

export function Test():void;

export function ToggleAboutModal():void;
