// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Quit() {
  window['go']['main']['App']['Quit']();
}

export function Test() {
  window['go']['main']['App']['Test']();
}

export function ToggleAboutModal() {
  window['go']['main']['App']['ToggleAboutModal']();
}
