name: Release
jobs:
  build:
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        build: [
          { name: Papyri, platform: linux/amd64, os: ubuntu-latest },
          { name: Papyri, platform: windows/amd64, os: windows-latest },
          { name: Papyri, platform: darwin/universal, os: macos-latest }
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
      - name: 'Build ${{ matrix.build.platform }}'
        uses: 'dAppServer/wails-build-action@v2'
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
  update-release-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    tags:
      - 'v*'